import React from 'react'

const Privacypolicy = () => {
  return (
    <div style={{width: "85%", boxShadow: "rgba(0, 0, 0, 0.35) 0px 5px 15px", textAlign:"center", margin:"auto"}}>
        <h1 style={{fontSize:"30px", fontWeight: "600", textDecoration: "underline", marginBottom:"10px"}}>Privacy Policy</h1>
        <p className='p-text-left'>1.  This privacy policy of businessworldtrade.com is applicable to all confidential personal information that is collected on the site. In this policy, the site highlights how and why we tend to collect all relevant and accurate personal information and how we make use of it.</p>
        <p className='p-text-left'>2. businessworldtrade.com is dedicated to comply with legislations of governing privacy of confidential personal information by business and protects all your privacy in the best possible manner when you make deals with us.</p>
        <p className='p-text-left'>3. Personal information collected from different people so that if you contact us for any issue, query, we keep complete record of that correspondence in the best effort basis. It can helps us to find solution and do root cause analysis of any issue or query raised by you.</p>
        <p className='p-text-left'>4. The personal data collected by us is a step to make you aware of who we are, we also allow you to gain access to information held about you.</p>
        <p className='p-text-left'>5. Use of information collected and disclosure of personal information to others. We might use or disclose any personal information that is held about an individual’s primarily for the purpose which it is collected. Such information may be collected for a purpose of maintaining records. The information is not disclosed to unwanted people. The information here is disclosed to people outside the periphery of our business in the situations set out in this policy or otherwise notified to you at the time of collection of the data.</p>
        <p className='p-text-left'>6. When we suspect an unlawful action or may be engaged in or has been a part of the disclosure, it becomes important for us to investigate and report the matter to the relevant authorities.</p>
        <p className='p-text-left'>7. When such disclosure is must under authorized law</p>
        <p className='p-text-left'>8. Where we believe that the use of the revelation is essential for the refrainment, investigation, punishment and prosecution of crimes or wrongdoings for conduct of proceedings afore any court or tribunal for the implementation of the order of the court or tribunal by the enforcement body.</p>
        <p className='p-text-left'>9. Website may contain links of other websites and those of third parties that may collect personal information about you in which we are not liable in any manner. We are not at all responsible for the private practices of other businesses or the data on the websites that are linked to our websites. We on our platform encourage users to stay aware when they leave the site and read the privacy statements of each and every linked website.</p>
        <p className='p-text-left'>10. Our platform places a great emphasis on the security of the information that is associated with our customers and contractors. We have complete security measures that protects against loss, alteration and misuse of any personal information that is under our control.</p>
        <p className='p-text-left'>11. Personal information is to be de-identified or to be destroyed securely when no longer required by us.</p>
        <p className='p-text-left'>12. The businessworldtrade.com retains the information you dole out to us and comprises your contact and all credit details to ensure us that you verify transactions and customer details for adequate records for legal and accounting purposes.</p>
        <p className='p-text-left'>13. All the major information stored with our computer can only be accessed by trust worthy authorities.</p>
        <p className='p-text-left'>14. No data ought to be transmitted over digital world is 100 per cent secured. While we ensure to protect all personal information of yours, but anything transferred over internet or via online means of communication we don’t provide warranty or guarantee in that case. The businessworldtrade.com receives your transmission and makes effort to ensure its security on its systems.</p>
        <p className='p-text-left'>15. Finally users are solely responsible for keeping their passwords or any form of account information secret. You ought to be careful and responsible whenever you are online. You must not share your password with any one for safety and you shall be solely responsible for keeping privacy of your account.</p>
        <p className='p-text-left'>16. Access to and correction of personal information We at businessworldtrade.com are dedicated to maintain authentic and accurate information of our customers in the best possible manner.</p>
        <p className='p-text-left'>17. we will provide you with the access to that information. if it is required by compliance.</p>
        <p className='p-text-left'>18. You shall be solely responsible for any inaccurate information provided by you , we are not liable for any inaccurate information given by you.</p>
        <p className='p-text-left'>19. Complaints: If you have any complaints Email us at complaints@businessworldtrade.com, support@businessworldtrade.com or Submit at https://www.businessworldtrade.com</p>
        <p className='p-text-left'>20. Contacting us: If you need any information please contact us at the following address: E-mail: support@businessworldtrade.com</p>
        <p className='p-text-left'>21. Acceptance: You accept that your use of this site includes your acceptance of this Privacy Policy and the Terms of Use</p>
        <p className='p-text-left'>Refund/Money Back Policy</p>
        <p className='p-text-left'>Once subscribed & the paid services activated on businessworldtrade.com, the payment made by the User for activated Paid service is not refundable under any circumstances and no claim for refund would be entertained. businessworldtrade.com neither offers any guarantees for the accuracy, timeliness, authenticity nor advocates any of the content posted by the other Users. All the services are on a best effort basis.</p>
        <p className='p-text-left'>businessworldtrade.com neither offers any guarantees for the accuracy, timeliness, authenticity nor advocates any of the content (Inquries, Product Listing, Catalog) posted by the other Users. All the services are on a best effort basis. So Under any circumstances businessworldtrade.com is not liable to refund.</p>
        <p className='p-text-left'>businessworldtrade.com shall not be liable in the event of any miscommunication between the client and the Sales Agent (Business Consultant). businessworldtrade.com neither offers any guarantees for Business Deal & Return on Investment All the services are on a best effort basis where our team try to give best business opportunities through platform advertising. No refund shall be initiated at any kind of circumstances with regard to the services already activated. So Before doing anything Please understand & read all the Policy / Terms & Condition / Subscription everything on businessworldtrade.com. For further confirmation Please get written confirmation only from support@businessworldtrade.com</p>
        <p className='p-text-left'>businessworldtrade.com does not represent the seller or the buyer in transactions and does not charge any commission for enabling any transaction. businessworldtrade.com does not control and is not liable to or responsible for the quantity, quality, safety, lawfulness or availability of the products or services offered for sale on the Web Site or the ability of the suppliers to complete a sale or the ability of buyers to complete a purchase. User(s) are cautioned that there may be risks of dealing with foreign nationals or people acting under false pretences on the Web Site. Web Site uses several tools and techniques to verify the accuracy and authenticity of the information provided by User(s). businessworldtrade.com however, cannot and does not confirm each User(s)’s purported identity on the Web Site. businessworldtrade.com encourages User(s) to evaluate the User(s) with whom they would like to deal with and use the common prudence while dealing with them. So Under any kind of circumstances businessworldtrade.com is not liable to refund</p>
        
    </div>
  )
}

export default Privacypolicy
