import React from 'react'

const TermsConditions = () => {
  return (
<div style={{width: "85%", boxShadow: "rgba(0, 0, 0, 0.35) 0px 5px 15px", textAlign:"center", margin:"auto"}}>
        <h1 style={{fontSize:"30px", fontWeight: "600", textDecoration: "underline", marginBottom:"10px"}}>Terms & Conditions</h1>
        <p className='p-text-left'>1."Company" means "Infobiz world trade Pvt. Ltd." and includes businessworldtrade.com where the context so requires.</p>
        <p className='p-text-left'>2."Advertiser" means the person or seller, company or other entity that wishes to advertise and avail of the services provided by the Company and whose name is set forth adjacent to the term "Advertiser" appearing overleaf.</p>
        <p className='p-text-left'>3.The rates mentioned herein are applicable for this transaction alone. The Company will have the right to change the advertising rates at any given point of time. without notice</p>
        <p className='p-text-left'>4. The personal data collected by us is a step to make you aware of who we are, we also allow you to gain access to information held about you.</p>
        <p className='p-text-left'>5. The Company "Infobiz world trade Pvt. Ltd." will have the sole discretion, at all times, to reject the Advertisement and further does not guarantee any particular position or place in the directory/website for the display of the Advertisement.</p>
        <p className='p-text-left'>6. The Company will take every reasonable precaution to publish the information, as supplied by the Advertiser, in the directory. However, the Company will not be responsible in case of any errors or omissions. But company is committed to edit/correct the errors or omissions and when he same is communicated by the adviser in writing wherever changes are possible.</p>
        <p className='p-text-left'>7. The Company reserves the right to make any modifications, if considered necessary or desirable in an Advertisement.</p>
        <p className='p-text-left'>8. Unless the Company and the Advertiser otherwise agree in writing, the Advertisement (excluding the trademarks and/or trade name of the Advertiser) used in preparation of the artworks will be the exclusive property of the Company. The Advertiser hereby warrants that the artwork design by the Company in any of its publications will not be reproduced or assigned for reproducing as a whole or in part, without the prior written consent of the Company.</p>
        <p className='p-text-left'>9. Advertising agency involved in placing the Advertisement for and on behalf of any person, company or entity ("Ultimate Customer") assures that it has the authority to modify and/or amend an Advertisement of an Ultimate Customer, in accordance with Advertiser's instructions without committing any offence or tort. The Advertiser hereby warrants and agrees that it shall indemnify and hold the Company harmless to the extent of any costs, damages or other charges falling upon the Company as a result of any claim and/or dispute raised by the Ultimate Customer against the Company arising from or relating to publication of the Advertisement.</p>
        <p className='p-text-left'>10. The Advertiser hereby represents and warrants that: 1. he is the owner of products and/or services that he wants advertised; and/or</p>
        <p className='p-text-left'>11. The Advertiser hereby agrees to notify the Company in writing of any change in ownership or authorization as aforesaid, which occurs after the execution of this invoice.</p>
        <p className='p-text-left'>12. The Advertiser hereby agrees to defend at its own, indemnify and keep the Company harmless from any infringement claims, losses and judgments which arise from or which are claimed to have arisen from the use of such copy cuts, illustrations, marks and names and Directories, the Advertisement and/or any Advertisement related material including but not limiting to any third party infringement claims together with expenses, attorney fees and court costs incurred by the Company.</p>
        <p className='p-text-left'>13. The Advertiser assumes sole responsibility and liability for protection of its Intellectual Property right(s) in any writing, pictorial illustration design format, photograph or combination thereof included in the Advertisement.</p>
        <p className='p-text-left'>14. Under no circumstances shall the Company or its associates be liable for any direct, indirect, incidental, special, consequential or exemplary damages, (even if the Company has been advised of the possibility of such damages) resulting from or in connection with the use of by the Advertiser of any of Infobiz world trade's services, including but not limiting to, damage(s) for loss of profits, goodwill, use, data or other intangible losses. Such limitation shall also apply with respect to damages incurred by reason of other services or products received through or advertised in connection with the Company, regardless of any negligence arising out of any of its services.</p>
        <p className='p-text-left'>15. Without prejudice to the aforesaid, the Company's liability under any circumstances is limited to the amount of fees, if any, paid by the Advertiser to the Company.</p>
        <p className='p-text-left'>16. In the event of any dispute between the Advertiser and the Company under, in connection with or in relation to this invoice, the same will be adjudicated by the courts of competent jurisdiction at Noida only, and in exclusion of all other courts that may have jurisdiction in the matter.</p>
        <p className='p-text-left'>17. This invoice shall be governed and construed in accordance with the laws of India without reference to its conflict of laws principles.</p>
        <p className='p-text-left'>18. In addition to the terms and conditions set forth in the invoice, and unless repugnant to the meaning or context thereof, the Advertiser hereby agrees and acknowledges that the User Agreement/Terms and Conditions, as reproduced on the businessworldtrade.com website 'businessworldtrade.com' ("T &Cs") are applicable to this invoice and are deemed to be incorporated herein by reference. In the event of any conflict or inconsistency between this invoice and the "T & Cs", the latter shallprevail.</p>
        <p className='p-text-left'>19. All correspondence to the Advertiser shall be sent to the address set forth overleaf and all correspondences to the Company should be addressed to our Registered Office.</p>
        <p className='p-text-left'>20. In case, due to whatever reason(s) if any advertiser asks for cancellation of advertisement(s), 35% of the amount paid will be deducted by the company as cancellation charge. Additionally ,on pro-rata basis deductions from the total amount paid by the advertiser will be done as per the consumption of advertisement based on the live duration of the given advertisement vis-a-vis total period booked.</p>
        <p style={{fontSize:"20px"}}>USER AGREEMENT</p>
        <p className='p-text-left'>Defined Terms Unless repugnant to the subject or context, the words appearing herein below shall have the meanings as set forth below:</p>
        <p className='p-text-left'>1."Agreement" shall mean this User Agreement and shall include the User application form duly completed, its attachment(s) and the terms and conditions stated herein and includes the documents incorporated by reference including the Illegal/Prohibited Content, Disclaimer, Warning against Fraud, Contract Form/Bill terms and conditions and such other documents that Company may in its absolute discretion add to the Site from time to time. It shall be deemed to have been executed at New Delhi.</p>
        <p className='p-text-left'>3."VR Trust Certificate" means The Company uses several tools and techniques to verify the accuracy of the given information by its registered Users. For the comfort of Users, Company offers the VR Trust certificate tool (3rd party verified report) which provides Users with more authentic information about a listed company (wherever applicable). We encourage Users to use VR Trust Certificate tool available on the Site, as well as business sense, to evaluate with whom the User is dealing. However, in no event shall the Company be liable for any direct, indirect, incidental, punitive, or consequential damages of any kind whatsoever with respect to the offered tool, services and/or the contents thereof. The Company hereby specifically disclaims any liability on account of a User's reliance upon any content.</p>
        <p className='p-text-left'>"Company" means Infobiz world trade Pvt. Ltd., registered office at C-125, GROUND FLOOR, SECTOR 2 NOIDA Gautam Buddha Nagar UP 201301 IN, along with its unit for the Company's website called businessworldtrade.com and where the context so requires, means and includes all Infobiz world trade Pvt. Ltd.'s officers, directors, employees and subsidiary, associate and affiliate entities, and/or business entities with whom Infobiz world trade Pvt. Ltd. enters into a partnership or strategic or financial alliance.</p>
        <p className='p-text-left'>"Credit Report" is a third party paid service provided to a User to obtain information about another company or legal entity, including detailed analytical information about profitability, past and present trading analysis and ownership essentially with a view to analyze their credit rating and stability.</p>
        <p className='p-text-left'>"Customized Header Catalog" is a subtype of On-line Catalogs that allow the customer to have catalog designed to his taste, however the functionalities available on the Catalog are fixed and are a part of the standardized offering.</p>
        <p className='p-text-left'>"Customized Websites" is a platform for Users to showcase their products or services on the Site.</p>
        <p className='p-text-left'>"Date of Termination" means the date when the User's subscription comes to an end. It shall be specified by the Company in its notice to the User either through e-mail or conventional mail.</p>
        <p className='p-text-left'>Agreement between User and Company</p>
        <p className='p-text-left'>The User understands that the Company through the Site provides hosting services to its Users. All Content listed on the Site is third party User generated content which is transmitted and/or hosted on the Site. Company neither originates nor initiates the transmission nor selects the sender and receiver of the transmission, nor modifies the information contained in the transmission.</p>
        <p className='p-text-left'>The Site is operated by Infobiz world trade Pvt. Ltd. and its affiliates/associates. The Services are offered to the User conditioned on the acceptance of the User without modification of the terms, conditions, and notices contained herein. Use of the Site by a User constitutes agreement to all such terms, conditions, and notices. If the User does not agree with any part of the Agreement, these terms, conditions and notices, it/they must not use the Services.</p>

        <p className='p-text-left'>Most content and some of the features on the Site is made available to Users free of charge. However, Company reserves the right to terminate access to certain areas or features of the Site to Users at any time with or without giving any reason, with or without notice. Company also reserves the universal right to deny access to particular Users to any/all of its Services and/or content without any prior notice/explanation in order to protect the interests of Company and/or other visitors to the Site. Company reserves the right to limit, deny or create different type access to the Site and its content features with respect to different User(s), or to change any of the features or introduce new features without prior notice.</p>
        <p className='p-text-left'>Company reserves the right to list its registered Users on the Site and as well as on other network portals run by the Company. In case a User does not want to be listed on the Site or on any of our network portals, they can communicate the same to us in writing by sending an email to info@businessworldtrade.com</p>
        <p className='p-text-left'>Users are advised to exercise due caution while transacting with a prospective buyer or a seller on the Site. Users must undertake interaction or transaction with organizations and/or individuals located on or through the Site, with reasonable caution and after undertaking thorough diligence on such organization and/or individual. Neither the Company nor its director’s, employees, officers or agents shall be liable to any User or otherwise, for any illegal or fraudulent interaction or transaction with organizations and/or individuals located on or through the Site.</p>
        <p style={{fontSize:"20px"}}>WARNING AGAINST FRAUD:</p>
        <p className="p-text-left">FRAUD WARNING All Users are advised to be very careful while doing business with individuals, body corporates or companies from any part of the world. Users are advised to exercise due caution while transacting with a prospective buyer or a seller on the Site. Users must undertake interactions or transactions with organizations and/or individuals located on or through the Site, with reasonable caution and after undertaking thorough diligence on such organization and/or individual. Neither the Company nor its director’s, employees, officers or agents shall be liable to any User or otherwise for any illegal or fraudulent interaction or transaction with organizations and/or individuals located on or through the Site. Users are advised to not send any advance money/legal fee or products unless there is cash in your account or an irrevocable letter of credit from the buyer, duly authorised by the buyer’s bank. Users are advised not to transact business unless full payment is made to you before shipping of the products. CREDIT CARD SCAMS - When a User receives any online Order paid by Credit Card, it is recommended that you ask for a written Credit Card Authorisation to be faxed to you. Please get validity of the Credit Card checked with your Bank or contact VISA, Master Card or American Express directly. Unless the validity of the Credit Card is confirmed, please do not ship any goods. BANK DRAFT SCAMS - BANK DRAFT SCAMS - There have been cases of people receiving Bank Drafts with unauthorised printing of Bank Names. Before shipping any product or advancing a partial cash advance, you must wait for the Bank to clear the Bank Draft/Check. Registration/License/Tender Fee SCAMS - Cases have been reported where an offer is sent to buy a large number of goods after the seller pays them a Registration/License/Tender Fee. They post Offers to BUY large quantity of Computers and other material. Once you submit your bid; you will be notified that your Tender has been accepted. You will then be asked to pay for Legal fees and Tender Fee. DO NOT PAY ANY FEE. Don't ship any Computers/Other products unless you have the cash in your account confirmed by your bank.</p>
        <p className="p-text-left">This document is an electronic record in terms of the Information Technology Act, 2000 and the provisions pertaining to electronic records in various statues amended by the Information Technology Act, 2000.</p>
        <p style={{fontSize:"20px"}}>DISCLAIMER</p>
        <p className="p-text-left">Company as well as its management have created these pages and the Services as a specific feature and as a service to the global exim community.</p>
        <p className="p-text-left">No warranty or condition expressed or implied or statutory is being provided to the User. Company hereby specifically disclaims any quality, durability, accuracy, reliability and all express or implied warranties including but not limited to warranties of title, merchantability, fitness for a particular purpose or performance. Company does not make any representation or warranties of any kind about any product or Services offered, or displayed or hosted on the Site. All such warranties, representations, conditions and undertakings are hereby excluded.</p>
        <p className="p-text-left">Under no circumstances shall Company be held liable for any delay or failure or disruption of the content or services delivered through the Site resulting directly or indirectly from acts of nature, forces or causes beyond our reasonable control, including without limitation, internet failures, computer, telecommunications or any other equipment failures, electrical power failues, strike, labor disputes, riots, insurrections, civil disturbances, shortage of labor or materials, fires, flood, storms, explosions, acts of God, war, governmental actions, order of domestic or foreign courts or tribunals or non-performance of third parties or other force majeure condition.</p>
        <p className="p-text-left"> Listing of counterfeits, non-licensed replicas or unauthorized products is strictly prohibited on the site. Further no products can be advertised on the site without the explicit permission from the intellectual property right holder. It is clear inter-alia that all third party intellectual property rights are owned by the third party and not Infobiz world trade Pvt. Ltd./its users. Under no circumstances will Company be liable, direct, indirect, incidental, special, consequential or exemplary damages including but not limited to, damages for loss of profit, goodwill, use, data or other intangible losses arising out of or in connection with the use of the Services provided by Company (“Damages”) whether arising out of or in connection with or otherwise in relation to any business or other transaction conducted in relation to the Service(s). The Company’s liability is limited in any and all circumstances shall be limited to the lesser of the amount of fees and/or charges paid by the User or Rs. 10,000/- (Indian Rupees Ten Thousand)</p>
        <p className="p-text-left">The User hereby indemnifies and holds Company harmless against any and all losses, claims, injuries and Damages that may arise out of the User’s breach of this Disclaimer and/or the Agreement, Illegal/Prohibited Content, Warning against Fraud and or any breach of the terms and conditions or the representations or warranties made by the User herein or in the Agreement/usage terms.</p>
        <p className="p-text-left">Company reserves the right to change the nature of the paid Services offered here or discontinue its Services to a member without any prior notice.</p>
        <p className="p-text-left">This document is an electronic record in terms of the Information Technology Act, 2000 and the provisions pertaining to electronic records in various statues amended by the Information Technology Act, 2000.</p>

    </div>
  )
}

export default TermsConditions
